### ISSUE TITLE
New food source

### ISSUE THREAD

**Issue by avdept** [Kromster80/kam_remake#13]
What do you think about adding bee hive, which generates honey? Hive should only work if there's fields nearby or trees. Also provide different grade honey depending on (fieds || trees)

**Comment by TehPlayer14** [comment]
Its takes too long to make a new food item or just the building itself.

Just no we are trying to make it like original game.

**Comment by avdept** [comment]
@Michal1324 Long - you mean to code stuff ?

**Comment by TehPlayer14** [comment]
NOT JUST CODE SPRITES for the thing building and animations and balance.

**Comment by Kromster80** [comment]
From the top of my head:
- we already have 4 distinct food types covering wide range of strategies
- KaM Remake is intended to be a remake, with minimal deviation from the original game
- we don't have artists ready to draw all the sprites at required level of quality to match KaM
