### ISSUE TITLE
Compile on mac os platform

### ISSUE THREAD

**Issue by avdept** [Kromster80/kam_remake#16]
Is it possible at all?

**Comment by TehPlayer14** [comment]
Well Opengl is cross platfrom not sure on the rest of stuff.

It might be

**Comment by avdept** [comment]
Is there list of 3rd party libs that are used in project?

**Comment by TehPlayer14** [comment]
its for example libzplay.dll

**Comment by Kromster80** [comment]
We did not make the OSX compilation because it requires a lot of work for no gain - the game works just as well under Wine.

**Comment by avdept** [comment]
@Kromster80 Could you point me, which parts of code are required to change in order to make it work on osx native?

**Comment by Kromster80** [comment]
You need Delphi XE2+ iirc. Then you need to make wrappers for APIs (OpengL, OpenAL, Net). Feel free to fork and ask questions! email or skype (kromster80)

**Comment by avdept** [comment]
AFAIK there's no deplhi studio for mac os, only lazarus, which is not same as xe2+. I will try anyway and report results.

**Comment by Kromster80** [comment]
IIRC it was XE2 when they introduced OSX compiler into Delphi IDE. I had successfully used it for other projects.

**Comment by avdept** [comment]
@Kromster80 I meant to use ide on mac, since i don't have windows installed(and not really want to do that). But in case i wont be able to compile via lazarus, i install windows on parallels

**Comment by Kromster80** [comment]
Yeah, use Parallels or dual-boot ;-)

**Comment by TehPlayer14** [comment]
Use Vmware or vbox if its avalible on mac

**Comment by Kromster80** [comment]
Closing, since OSX compilation requires a lot of work for very little gain - the game works under Wine.
