### ISSUE TITLE
License is not specified

### ISSUE THREAD

**Issue by wenzeslaus** [Kromster80/kam_remake#191]
What is the license of the project? The source code license is not specified in the LICENSE file, README, nor in the code.

**Comment by Kromster80** [comment]
Previously on Google Code we used GPL 2.
We have discussed it now and decided on upgrading to AGPL 3.0.
Appropriate headers will be added to source code files soon.

**Comment by reyandme** [comment]
There is a Licence file now in project root dir. 
Can we close this issue? Or we still need to specify licence info somewhere else ?

**Comment by Kromster80** [comment]
My bad, I've added them and forgot to close the issue )
