### ISSUE TITLE
Clickable links in chat (Memo)

### ISSUE THREAD

**Issue by reyandme** [Kromster80/kam_remake#195]
Recently I added possibility to select text in chat (Edit and Memo).
@lewinjh @Kromster80 What do you think about clickable links there too? 
Is it ok or it could be abused with 'bad' links or smth like this?

**Comment by Kromster80** [comment]
It is dangerous and could be abused (including for spam). Better let players select the text and copy-paste it into browser, so they have a conscious decision of going over the link.

**Comment by reyandme** [comment]
I close this Issue then
