### ISSUE TITLE
Do not show color on minimap for corn/wine fields

### ISSUE THREAD

**Issue by reyandme** [Kromster80/kam_remake#243]
These field are actually common for any player.

Also there is field abuse now: player can place a lot of fields on the map after PT to disguise his army from being spoted on minimap. After PT lots of workers usually have nothing to do, many players even "dispose" them by sending to enemies. So they can easily do this "mask" task for free. 

There are also wine and road tiles. Roads should be painted for sure, because the make "city view" on minimap, linking all buildings together. But wine is not so important. Even if its not possible to abuse it, I believe it still better not to paint them, for generality with not colored fields.

**Comment by Kromster80** [comment]
I'm in favor of this change. IIRC it was requested from forums a long time ago.

**Comment by reyandme** [comment]
@lewinjh what do you say, can I start implementing this ?

**Comment by lewinjh** [comment]
Sounds ok to me. It will mean there are holes in the minimap in bases where fields are. But it's worse if you use it to look like an army on the battlefield, especially given that players often place fields to suicide their workers. So yes, go ahead and implement it :)

**Comment by reyandme** [comment]
implemented in #261
