### ISSUE TITLE
Compiling issues Embarcadero RAD XE8

### ISSUE THREAD

**Issue by LauraRozier** [Kromster80/kam_remake#32]
After adding the proper new define in KaM_Remake.inc, which is:
{$IFDEF VER290} {$DEFINE WDC} {$ENDIF} //Define Windows Delphi XE8 compiler

Pull request for that will follow.

I get a rather big list of errors and warnings and compilation fails.

Here an image of the list:

![screenshot_1](https://cloud.githubusercontent.com/assets/12035362/7410530/0055c232-ef30-11e4-8e99-e0983e7a041e.png)

**Comment by Kromster80** [comment]
We don't plan to upgrade project to support XE8 for now
