### ISSUE TITLE
Changes to Actions.PlayerShareFog breaks backwards script compatibility

### ISSUE THREAD

**Issue by lewinjh** [Kromster80/kam_remake#321]
@andreus791 We want to maintain backwards compatibility if possible so old r6720 scripts still work in the next release without script authors having to fix them all. Can we add a new Actions.PlayerShareFogCompliment? Or simply remove the compliment parameter since it can be achieved by running:
Actions.PlayerShareFog(A, B, True)
Actions.PlayerShareFog(B, A, True)
?

**Comment by andreus791** [comment]
Yeah I forgot about back compatibility... Maybe new script with additional parameter will be better (like GiveField/GiveFieldAged).

**Comment by reyandme** [comment]
fixed in #325
