### ISSUE TITLE
Allow to play the map with a shortcut from MapEditor

### ISSUE THREAD

**Issue by TehPlayer14** [Kromster80/kam_remake#372]
Test a map without needing to save it and then test it through menu

**Comment by Kromster80** [comment]
That would be good :-)

**Comment by reyandme** [comment]
Yes, I was thinking to add this feature too. 
Going to implement it soon.
Probably we can add this new button next to save/load buttons.

**Comment by reyandme** [comment]
Implemented in my repository

**Comment by TehPlayer14** [comment]
Implemented can be closed
