### ISSUE TITLE
Resource depleted notification should handle new houses built on the same spot

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/kam_remake#38]
1. Build Fisherman's
2. Wait for Fisherman's to catch all fish and get "no more fish available" notification
3. Demolish Fisherman's
4. Build another house on the same spot
5. Click notification from step 2
6. New house will be highlighted

Step 6 should not highlight the new house (but still could bring to that location?).

**Comment by vqw** [comment]
The same happens with stonemason/woodcutter/coal mine.

**Comment by Kromster80** [comment]
No surprise, because they all share the same notification mechanism.

**Comment by vqw** [comment]
Yup, 'house not occupied' is affected as well.

**Comment by vqw** [comment]
The function has been tweaked for this condition - creating pull request

**Comment by vqw** [comment]
It's fixed with pull request 40, please close
