### ISSUE TITLE
if States then variable := number;

### ISSUE THREAD

**Issue by petrmenzel** [Kromster80/kam_remake#412]
```
...
21 procedure nameofprocedure(aPlayer: Integer);
22 begin
23      LU_ID24 := States.ClosestUnit(aPlayer,1,1,24);
24      if (States.UnitAt(7,1) = LU_ID24) then aStuff1 := 2;
25      begin
26           _code_
27      end;
28 end;
...
```
**(24:5) Identifier expected**

Any help? Thx you very much.

**Comment by TehPlayer14** [comment]
As I said please use Kam Remake forum http://www.knightsandmerchants.net/forum/index.php
This is wrong place for this

**Comment by reyandme** [comment]
I agree with Michal. 
And provide your full script there.

**Comment by Kromster80** [comment]
Dynamic script has proven to be quite reliable. 99% of bugs are due to mistakes in written code. So please try to post about it in forum first, and only then, when the bug is confirmed - post the MVCE (Minimal, Complete, and Verifiable example) to KMR Issues.
Thanks.
