### ISSUE TITLE
Horses are not included into warfare results, but are counted as warfare in charts

### ISSUE THREAD

**Issue by Kromster80** [Kromster80/kam_remake#81]
Game results "Warfare made" counter does not include horses.
Game results "Warfare" chart includes horses.

Decision should be made and reasoned, if horses do count as warfare.
All warfare instances should be checked and synced.

**Comment by lewinjh** [comment]
Fixed in PR #179 

Horses are now counted as warfare. My logic is:

We include shields/armour (which are not weapons) so why not horses? They are a ware that you produce like other weapons and they are used exclusively to equip soldiers. So IMO they should be counted as weapons for stats purposes.
