### ISSUE TITLE
OpenAL include

### ISSUE THREAD

**Issue by Jogai** [Kromster80/kam_remake#88]
Dropping openal32.dll from blender in de kam_remake folder is enough. Maybe it can be distributed like that as wel?

**Comment by Kromster80** [comment]
It is better to distribute the drivers, as they might change or be different on clients PCs.

**Comment by Jogai** [comment]
The drivers are installed in windows. OpenAl should connect to these drivers to produce sound.  

Blender uses [OpenAl soft](http://kcat.strangesoft.net/openal.html), maybe that works better with a binary distribution model.

**Comment by LauraRozier** [comment]
KMR uses the official OpenAL package, which contains a driver DLL.
This is the 'openal32.dll' but then the official version.
[openal.org](https://www.openal.org/downloads/)

The benefit of using the installer is that you will not break any licenses etc.
The installer will also provide it's own 'end-user consent' question ( The 'are you sure you wish to install this software' question ) and that it will show the EULA question.
