### ISSUE TITLE
Automatically pause the replay on peacetime

### ISSUE THREAD

**Issue by sado1** [Kromster80/kam_remake#91]
While watching a multiplayer game replay, people often want to 'skip' the building phase right to the peacetime, to see the contents of the barracks. However, without support for rewinding a replay (and with such support unlikely to happen without some big changes to the way replays work), if you try to skip to the peacetime on a higher speed, it's very easy to miss the peacetime, which makes you unable to see the numbers after the units get trained. The feature might be optional, like the fog display.

**Comment by Kromster80** [comment]
Good idea!
I recall it was discussed somewhere, but I can not find it in todo lists, so let it be accepted here.

**Comment by reyandme** [comment]
Implemented in PR #136
