### ISSUE TITLE
Option to hide the UI elements in replays and in spectate mode

### ISSUE THREAD

**Issue by sado1** [Kromster80/kam_remake#92]
For the purposes of recording videos and streaming, it would be nice to be able to hide the replay overlay in both replays and spectator mode. Proposed idea could work similar to how the scripting overlay is hidden; by clicking on the '+' button.

**Comment by Kromster80** [comment]
Are replay controls that obtrusive in replays recording?

I would assume they are nice to see (to know the match length and playtime position). Also for recording and streaming replay panel could be easily covered with some element.

I'm in favor of rejecting this idea.

**Comment by sado1** [comment]
You might be right, this is a minor thing and after reconsideration I agree this isn't really needed.
